CREATE TABLE CATEGORIA (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORIA (NAME) VALUES ('Laser');
INSERT INTO CATEGORIA (NAME) VALUES ('Alimentação');
INSERT INTO CATEGORIA (NAME) VALUES ('Supermercado');
INSERT INTO CATEGORIA (NAME) VALUES ('Farmacia');
INSERT INTO CATEGORIA (NAME) VALUES ('Outros');
