CREATE TABLE users (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	NAME VARCHAR(191) NOT NULL,
 	EMAIL VARCHAR(191) NOT NULL UNIQUE,
 	PASSWORD VARCHAR(191) NOT NULL,
 	DELETED_AT TIMESTAMP NULL,
 	CREATED_AT TIMESTAMP NULL DEFAULT NOW()
);
 
CREATE TABLE roles (
 	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 	NAME VARCHAR(191) NOT NULL,
 	DELETED_AT TIMESTAMP NULL,
 	CREATED_AT TIMESTAMP NULL DEFAULT NOW() 	
);
 
 
CREATE TABLE user_roles (
 	USER_ID BIGINT(20) NOT NULL,
 	ROLE_ID BIGINT(20) NOT NULL, 
 	CREATED_AT TIMESTAMP NULL DEFAULT NOW(),
 	
 	
 	FOREIGN KEY (USER_ID) REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES roles(id)  ON DELETE CASCADE
);

INSERT INTO users (ID, NAME, EMAIL, PASSWORD) VALUES (1, 'ADMIN', 'admin@gerobras.com', '{bcrypt}$2a$10$Unlnc/sbYyACLd9CksWyb.wiJImiQN6epu80A2IvI7T.OdqsuhkIy');

INSERT INTO roles (ID, NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (ID, NAME) VALUES (2, 'ROLE_CLIENT');

INSERT INTO user_roles (USER_ID, ROLE_ID) VALUES (1, 1);